import { useState } from "react";
import Head from "next/head";
import InputString from "@/components/input-screen/InputScreen";
import DuplicatesScreen from "@/components/duplicates-screen/DuplicatesScreen";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const [string, setString] = useState("");
  const [hasString, setHasString] = useState(false);

  const handleSubmit = (e) => {
    e.preventDefault();

    if (!string) {
      alert("Please enter a string");
      return;
    }

    setHasString(true);
  };

  const handleChange = (e) => {
    setString(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {!hasString ? (
          <InputString
            onHandleSubmit={handleSubmit}
            onString={string}
            onHandleChange={handleChange}
          />
        ) : (
          <DuplicatesScreen
            onString={string}
            onSetString={setString}
            onSetHasString={setHasString}
          />
        )}
      </main>
    </>
  );
}
